#!/bin/bash
# Create a temporary file
TMPFILE=$(mktemp)

# Add stuff to the temporary file
echo "source ~/.bashrc" > $TMPFILE
echo "source venv/bin/activate" >> $TMPFILE
echo "rm -f $TMPFILE" >> $TMPFILE


# Start the new bash shell 
bash --rcfile $TMPFILE
